### ISSUE TITLE
AssertionError in discrete action space when grasping

### ISSUE THREAD

**Issue by meier-johannes94** [StanfordVL/iGibson#145]
Hi, 
today I had the following error message, when I tried to grasp something in the discrete action space: 

```
Traceback (most recent call last):
  File "stable_baselines3_behavior_example.py", line 242, in <module>
    main()
  File "stable_baselines3_behavior_example.py", line 199, in main
    observations, rewards, dones, infos = env.step(action_id)
  File "/is/sg2/jmeier/behaviorchallenge/iGibson/igibson/envs/behavior_mp_env.py", line 172, in step
    self.grasp_obj(obj, hand)
  File "/is/sg2/jmeier/behaviorchallenge/iGibson/igibson/envs/behavior_mp_env.py", line 351, in grasp_obj
    override_ag_data=(obj.get_body_id(), -1),
  File "/is/sg2/jmeier/behaviorchallenge/iGibson/igibson/robots/behavior_robot.py", line 1060, in handle_assisted_grasping
    assert contact_pos is not None
AssertionError 
```

**Comment by meier-johannes94** [comment]
It seems as if this error occurs quite often. I think waiting for Christmas for the next update would be a bit long ;-). Can I fix this somehow?
