### ISSUE TITLE
Installation issue with cvpr21_challenge branch

### ISSUE THREAD

**Issue by kpant14** [StanfordVL/iGibson#226]
Ran into the following errors.
```
Obtaining file:///home/coral/iGibson
  Preparing metadata (setup.py) ... done
Collecting pyrvo2@ https://github.com/sybrenstuvel/Python-RVO2/archive/master.zip
  Using cached https://github.com/sybrenstuvel/Python-RVO2/archive/master.zip
  Preparing metadata (setup.py) ... done
Requirement already satisfied: gym>=0.12 in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (0.23.1)
Requirement already satisfied: numpy>=1.16.0 in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (1.22.3)
Requirement already satisfied: scipy>=1.2.1 in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (1.7.3)
Requirement already satisfied: pybullet>=2.6.4 in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (3.2.5)
Requirement already satisfied: transforms3d>=0.3.1 in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (0.3.1)
Requirement already satisfied: opencv-python>=3.4.8 in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (4.5.5.64)
Requirement already satisfied: Pillow>=5.4.0 in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (9.1.0)
Requirement already satisfied: networkx>=2.0 in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (2.8.4)
Requirement already satisfied: PyYAML in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (6.0)
Requirement already satisfied: tqdm in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (4.62.3)
Requirement already satisfied: matplotlib in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (3.5.2)
Requirement already satisfied: cloudpickle in /home/coral/.local/lib/python3.8/site-packages (from gibson2==1.0.1) (2.0.0)
Requirement already satisfied: aenum in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (3.1.11)
Requirement already satisfied: GPUtil in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (1.4.0)
Requirement already satisfied: ipython in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (8.4.0)
Requirement already satisfied: pytest in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (7.1.2)
Requirement already satisfied: future in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (0.18.2)
Requirement already satisfied: trimesh in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (3.12.7)
Requirement already satisfied: sphinx_markdown_tables in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (0.0.15)
Requirement already satisfied: sphinx>=1.8.0 in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (5.0.2)
Requirement already satisfied: recommonmark in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (0.7.1)
Requirement already satisfied: sphinx_rtd_theme in /home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages (from gibson2==1.0.1) (1.0.0)
Collecting Cython==0.21.1
  Using cached Cython-0.21.1.zip (3.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-89p9b7zg/cython_536c329279bc44dba03634327e23ac6f/setup.py", line 39, in <module>
          from distutils.command.build_py \
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/home/coral/anaconda3/envs/igibson/lib/python3.8/site-packages/setuptools/_distutils/command/build_py.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ChengshuLi** [comment]
Same issue as https://github.com/StanfordVL/iGibson/issues/227.

Let's discuss this in that thread. Thanks!
