### ISSUE TITLE
ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py'  when compiling gibson from source in anaconda environment following  https://stanfordvl.github.io/iGibson/installation.html 

### ISSUE THREAD

**Issue by G-KUMAR** [StanfordVL/iGibson#227]
pip install -e .
Obtaining file:///home/user/Documents/iGibson
  Preparing metadata (setup.py) ... done
Collecting pyrvo2@ https://github.com/sybrenstuvel/Python-RVO2/archive/master.zip
  Using cached https://github.com/sybrenstuvel/Python-RVO2/archive/master.zip
  Preparing metadata (setup.py) ... done
Requirement already satisfied: gym>=0.12 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (0.25.0)
Requirement already satisfied: numpy>=1.16.0 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (1.21.6)
Requirement already satisfied: scipy>=1.2.1 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (1.7.3)
Collecting pybullet>=2.6.4
  Using cached pybullet-3.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (91.7 MB)
Requirement already satisfied: transforms3d>=0.3.1 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (0.3.1)
Requirement already satisfied: opencv-python>=3.4.8 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (4.6.0.66)
Requirement already satisfied: Pillow>=5.4.0 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (9.2.0)
Requirement already satisfied: networkx>=2.0 in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (2.6.3)
Requirement already satisfied: PyYAML in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (6.0)
Requirement already satisfied: tqdm in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (4.64.0)
Requirement already satisfied: matplotlib in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (3.5.2)
Requirement already satisfied: cloudpickle in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (2.1.0)
Requirement already satisfied: aenum in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (3.1.11)
Requirement already satisfied: GPUtil in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (1.4.0)
Requirement already satisfied: ipython in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (7.34.0)
Requirement already satisfied: pytest in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (7.1.2)
Requirement already satisfied: future in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (0.18.2)
Requirement already satisfied: trimesh in /home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages (from gibson2==1.0.1) (3.12.9)
Collecting sphinx_markdown_tables
  Using cached sphinx_markdown_tables-0.0.15-py3-none-any.whl (28 kB)
Collecting sphinx>=1.8.0
  Using cached Sphinx-5.0.2-py3-none-any.whl (3.1 MB)
Collecting recommonmark
  Using cached recommonmark-0.7.1-py2.py3-none-any.whl (10 kB)
Collecting sphinx_rtd_theme
  Using cached sphinx_rtd_theme-1.0.0-py2.py3-none-any.whl (2.8 MB)
Collecting Cython==0.21.1
  Using cached Cython-0.21.1.zip (3.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kz4p4j26/cython_bbfe797b832546d18cd2780e57643952/setup.py", line 39, in <module>
          from distutils.command.build_py \
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/home/user/anaconda3/envs/iGibson/lib/python3.7/site-packages/setuptools/_distutils/command/build_py.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jbui007** [comment]
This post may help: https://psycopg.lighthouseapp.com/projects/62710/tickets/153  if you still having issue.
the package you try to install cannot do the import, so you need to patch the setup.py in that package for it to work.
