### ISSUE TITLE
ERROR: Could not build wheels for igibson, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by JiaoyangXu-hub** [StanfordVL/iGibson#231]
**I have installed cmake and the version of python is 3.8.13 in Ubuntu20.04 WSL. but there's a error when installing igibson with `pip install igibson`. snippet of the error message is here below :**

.......
running build_ext
      Traceback (most recent call last):
        File "/home/xu/anaconda3/envs/igibson/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      /tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'igibson.utils.data_utils.ext_scene.scripts.utils.data' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'igibson.utils.data_utils.ext_scene.scripts.utils.data' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'igibson.utils.data_utils.ext_scene.scripts.utils.data' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'igibson.utils.data_utils.ext_scene.scripts.utils.data' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'igibson.utils.data_utils.images' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'igibson.utils.data_utils.images' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'igibson.utils.data_utils.images' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'igibson.utils.data_utils.images' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'igibson.utils.data_utils.mesh_decimation' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'igibson.utils.data_utils.mesh_decimation' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'igibson.utils.data_utils.mesh_decimation' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'igibson.utils.data_utils.mesh_decimation' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'igibson.utils.data_utils.sampling_task' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'igibson.utils.data_utils.sampling_task' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'igibson.utils.data_utils.sampling_task' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'igibson.utils.data_utils.sampling_task' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      Traceback (most recent call last):
        File "/home/xu/anaconda3/envs/igibson/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/xu/anaconda3/envs/igibson/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/xu/anaconda3/envs/igibson/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 412, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 130, in <module>
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zijp66ax/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "<string>", line 44, in run
        File "/home/xu/anaconda3/envs/igibson/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/xu/anaconda3/envs/igibson/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for igibson
Failed to build igibson
ERROR: Could not build wheels for igibson, which is required to install pyproject.toml-based projects

**Comment by fxia22** [comment]
There is a problem `ModuleNotFoundError: No module named 'cmake'`

Can you try to install cmake first

**Comment by LeZheng-x** [comment]
it does not work even i install cmake ,       
 File "/home/****/anaconda3/envs/igibson2/bin/cmake", line 5, in <module>
    from cmake import cmake
      ModuleNotFoundError: No module named 'cmake' , but i can run from cmake import cmake in same conda env

**Comment by Wei-Nijuan** [comment]
but I have installed cmake

**Comment by ThomasP850** [comment]
I'm having the same issue, when I run `cmake --version`, it shows that I have CMAKE 4.0.0 installed and on the path. 

I'm on a Windows computer.
