### ISSUE TITLE
Build failing on mac

### ISSUE THREAD

**Issue by dhruvbatra** [StanfordVL/iGibson#28]
Probably because it needs CUDA? 

```bash
dbatra at dbatra-mbp in ~/iGibson on master
$ pip install -e .
Obtaining file:///Users/dbatra/iGibson
Requirement already satisfied: numpy==1.16.6 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (1.16.6)
Requirement already satisfied: scipy==1.2.3 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (1.2.3)
Requirement already satisfied: gym==0.12 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (0.12.0)
Requirement already satisfied: PyYAML in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (5.3.1)
Requirement already satisfied: pybullet==2.6.4 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (2.6.4)
Requirement already satisfied: transforms3d==0.3.1 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (0.3.1)
Requirement already satisfied: tqdm==4.19.9 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (4.19.9)
Requirement already satisfied: Pillow==6.1.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (6.1.0)
Requirement already satisfied: matplotlib==2.2.5 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (2.2.5)
Requirement already satisfied: cloudpickle==1.2.2 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (1.2.2)
Requirement already satisfied: opencv-python==4.2.0.32 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (4.2.0.32)
Requirement already satisfied: aenum==2.2.3 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (2.2.3)
Requirement already satisfied: GPUtil==1.4.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (1.4.0)
Requirement already satisfied: networkx==2.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (2.0)
Requirement already satisfied: ipython==5.9.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (5.9.0)
Requirement already satisfied: pytest==4.6.9 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (4.6.9)
Requirement already satisfied: future in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gibson2==0.0.4) (0.18.2)
Requirement already satisfied: six in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gym==0.12->gibson2==0.0.4) (1.14.0)
Requirement already satisfied: pyglet>=1.2.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gym==0.12->gibson2==0.0.4) (1.5.3)
Requirement already satisfied: requests>=2.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from gym==0.12->gibson2==0.0.4) (2.23.0)
Requirement already satisfied: pytz in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from matplotlib==2.2.5->gibson2==0.0.4) (2019.3)
Requirement already satisfied: cycler>=0.10 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from matplotlib==2.2.5->gibson2==0.0.4) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from matplotlib==2.2.5->gibson2==0.0.4) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from matplotlib==2.2.5->gibson2==0.0.4) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from matplotlib==2.2.5->gibson2==0.0.4) (1.2.0)
Requirement already satisfied: decorator>=4.1.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from networkx==2.0->gibson2==0.0.4) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (1.0.18)
Requirement already satisfied: pickleshare in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (0.8.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (0.1.0)
Requirement already satisfied: setuptools>=18.5 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (46.1.3.post20200330)
Requirement already satisfied: pygments in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (2.6.1)
Requirement already satisfied: traitlets>=4.2 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (4.3.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from ipython==5.9.0->gibson2==0.0.4) (4.8.0)
Requirement already satisfied: attrs>=17.4.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0; python_version > "2.7" in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (8.2.0)
Requirement already satisfied: packaging in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (20.3)
Requirement already satisfied: pluggy<1.0,>=0.12 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (0.13.1)
Requirement already satisfied: wcwidth in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (0.1.9)
Requirement already satisfied: py>=1.5.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (1.8.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (1.6.0)
Requirement already satisfied: atomicwrites>=1.0 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pytest==4.6.9->gibson2==0.0.4) (1.3.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from requests>=2.0->gym==0.12->gibson2==0.0.4) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from requests>=2.0->gym==0.12->gibson2==0.0.4) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from requests>=2.0->gym==0.12->gibson2==0.0.4) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from requests>=2.0->gym==0.12->gibson2==0.0.4) (2020.4.5.1)
Requirement already satisfied: ipython-genutils in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from traitlets>=4.2->ipython==5.9.0->gibson2==0.0.4) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython==5.9.0->gibson2==0.0.4) (0.6.0)
Requirement already satisfied: zipp>=0.5 in /anaconda3/envs/gibson2/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==4.6.9->gibson2==0.0.4) (3.1.0)
Installing collected packages: gibson2
  Running setup.py develop for gibson2
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/envs/gibson2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/dbatra/iGibson/setup.py'"'"'; __file__='"'"'/Users/dbatra/iGibson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/dbatra/iGibson/
    Complete output (60 lines):
    running develop
    running egg_info
    writing gibson2.egg-info/PKG-INFO
    writing dependency_links to gibson2.egg-info/dependency_links.txt
    writing requirements to gibson2.egg-info/requires.txt
    writing top-level names to gibson2.egg-info/top_level.txt
    reading manifest file 'gibson2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'gibson2.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is AppleClang 10.0.1.10010046
    -- The CXX compiler identification is AppleClang 10.0.1.10010046
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- pybind11 v2.3.dev0
    CMake Error at /anaconda3/envs/gibson2/share/cmake-3.14/Modules/FindCUDA.cmake:700 (message):
      Specify CUDA_TOOLKIT_ROOT_DIR
    Call Stack (most recent call first):
      CMakeLists.txt:35 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/Users/dbatra/iGibson/build/temp.macosx-10.9-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/dbatra/iGibson/setup.py", line 139, in <module>
        include_package_data=True,
      File "/anaconda3/envs/gibson2/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/envs/gibson2/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/envs/gibson2/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda3/envs/gibson2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/envs/gibson2/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/anaconda3/envs/gibson2/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/anaconda3/envs/gibson2/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/envs/gibson2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/dbatra/iGibson/setup.py", line 55, in run
        self.build_extension(ext)
      File "/Users/dbatra/iGibson/setup.py", line 89, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/anaconda3/envs/gibson2/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/Users/dbatra/iGibson/gibson2/core/render', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dbatra/iGibson/gibson2/core/render/mesh_renderer', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/dbatra/iGibson/gibson2/core/render/mesh_renderer/build', '-DPYTHON_EXECUTABLE=/anaconda3/envs/gibson2/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda3/envs/gibson2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/dbatra/iGibson/setup.py'"'"'; __file__='"'"'/Users/dbatra/iGibson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by fxia22** [comment]
Hi Dhruv, 
Thanks for the question, building on Mac should be possible, with a few features disabled (for example render to tensor, and also need glfw3 context as OS X has pool EGL support). We are working on a platform-dependent CMakeLists to make building on mac easier.

**Comment by dhruvbatra** [comment]
Makes sense. Good luck.

**Comment by fxia22** [comment]
This feature is added in version 0.0.5 per @dhruvbatra 's suggestion. Thanks a lot!
