### ISSUE TITLE
there is no metadata in the h5 file of the Raw virtual reality demonstration dataset (VR_demos_raw)

### ISSUE THREAD

**Issue by biguard** [StanfordVL/iGibson#351]
there is no metadata, which caused we can't read the content to reolay the demonstration, such as task, task_id and scene. All the content is none.

Traceback (most recent call last):
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 370, in <module>
    main()
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 361, in main
    replay_demo(in_demo_file, **args_dict)
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 231, in replay_demo
    env = iGibsonEnv(
  File "e:\pythonprojects\iGibson\iGibson\igibson\envs\igibson_env.py", line 62, in __init__
    super(iGibsonEnv, self).__init__(
  File "e:\pythonprojects\iGibson\iGibson\igibson\envs\env_base.py", line 108, in __init__
    self.load()
  File "e:\pythonprojects\iGibson\iGibson\igibson\envs\igibson_env.py", line 263, in load
    super(iGibsonEnv, self).load()
  File "e:\pythonprojects\iGibson\iGibson\igibson\envs\env_base.py", line 170, in load
    scene = InteractiveIndoorScene(
  File "e:\pythonprojects\iGibson\iGibson\igibson\scenes\igibson_indoor_scene.py", line 143, in __init__
    self.scene_tree = ET.parse(self.scene_file)
  File "E:\anaconda\envs\igibson\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "E:\anaconda\envs\igibson\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\pythonprojects\\iGibson\\iGibson\\igibson\\data/ig_dataset\\scenes\\Ihlen_0_int\\urdf\\Ihlen_0_int_task_None_None_0_fixed_furniture.urdf'

**Comment by biguard** [comment]
oh i know, the name of the definition is not the same. But there is other question:
Traceback (most recent call last):
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 370, in <module>
    main()
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 361, in main
    replay_demo(in_demo_file, **args_dict)
  File "e:\pythonprojects\iGibson\iGibson\demo_replaying_example.py", line 245, in replay_demo
    log_reader = IGLogReader(in_demo_file, log_status=False)
  File "e:\pythonprojects\iGibson\iGibson\igibson\utils\ig_logging.py", line 564, in __init__
    self.total_frame_num = self.hf["frame_data"].shape[0]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "E:\anaconda\envs\igibson\lib\site-packages\h5py\_hl\group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 189, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'frame_data' doesn't exist)"
